### ISSUE TITLE
ft.search  can't find value  by eval script

### ISSUE THREAD

**Issue by liamayi** [apache/kvrocks#2995]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

CentOS Linux release 7.9.2009 (Core)
kvrocks 2.12.1

### Minimal reproduce step

```
ft.create idx:m on hash prefix 1 m: schema signature tag

eval 'redis.call("HSET","m:toutiao:123","signature","12345")' 0

ft.search idx:m '@signature:{"12345"}'

```
### What did you expect to see?

expect result:
```
1
m:toutiao:123
signature
12345
```

but return 0

### What did you see instead?

0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liamayi** [comment]
ft.search idx:m '@signature:{"12345"}'

**Comment by PragmaTwice** [comment]
It depends on how you use EVAL. For example, in your case the correct way to use EVAL is
```
eval 'redis.call("HSET",KEYS[1],"signature","12345")' 1 m:toutiao:123
```

And then I think the recording part of search can work as expected.

---

Refer to redis doc: https://redis.io/docs/latest/commands/eval/

> Important: to ensure the correct execution of scripts, both in standalone and clustered deployments, **all names of keys that a script accesses must be explicitly provided as input key arguments**. The script should only access keys whose names are given as input arguments. Scripts should never access keys with programmatically-generated names or based on the contents of data structures stored in the database.

**Comment by liamayi** [comment]
thank you help 
I try it ,but not work

```
 eval 'redis.call("HSET",KEYS[1],"signature","12345")' 1 m:toutiao:123

eval 'redis.call("HSET",KEYS[1],ARGV[1],ARGV[2])' 1 m:toutiao:123  signature 12345
```


![Image](https://github.com/user-attachments/assets/48795214-347d-42ae-b01b-ae3d605c2363)

**Comment by PragmaTwice** [comment]
Ahh sorry, I've found the root cause now.

It will be fixed in #2998.

After this patch, the method I mentioned https://github.com/apache/kvrocks/issues/2995#issuecomment-2914656383 should work.

**Comment by PragmaTwice** [comment]
It's fixed in the unstable branch.

You can try it by using docker image `apache/kvrocks:nightly-20250528-2cd7e14`.

**Comment by liamayi** [comment]
I try it with apache/kvrocks:nightly-20250528-2cd7e14  ,but still not work
@PragmaTwice

**Comment by PragmaTwice** [comment]
![Image](https://github.com/user-attachments/assets/47b51aac-350e-4ce4-a357-f52d5c95cb39)

I've comfirmed it is fixed.

**Comment by liamayi** [comment]
I tried again and it's okay. Thank you very much @PragmaTwice
